name: emotion-game
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: emo-game-test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd node-js
          yarn install 
          yarn knex migrate:latest --env test
          yarn jest
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd emotion-game/node-js
          git pull origin main
          yarn install
          yarn knex migrate:latest --env production
          yarn knex seed:run --env production
          forever restart -c 'yarn start' .
        host: emogame.duncantang.dev
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
    - name: ssh to restart python
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd emotion-game/python
          git pull origin main
          pip install -r requirements.txt
          forever restart -c 'python app.py' .
        host: pythonAI.duncantang.dev
        user: ubuntu
        key: ${{secrets.PYTHON_SSH_PRIVATE_KEY}}