name: emotion-game
on:
  push:
    branches:
      - 'production'
  workflow_dispatch:

env:
  POSTGRES_DB: test-emogame
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing-node:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: test node server
        working-directory: node-js
        run: |
          yarn install 
          yarn knex migrate:latest --env test
          yarn jest
  deploy-node:
    runs-on: ubuntu-latest
    needs: testing-node
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      working-directory: node-js
      with:
        command: |
          git pull origin master
          yarn install
          yarn knex migrate:latest --env production
          yarn knex seed:run --env production
          forever restart -c 'yarn start' .
        host: emogame.duncantang.dev
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
  testing-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install package
        working-directory: python
        run: pip install -r requirements.txt
      - name: Run test
        working-directory: python
        run: python -m pytest
  deploy-python:
    runs-on: ubuntu-latest
    needs: testing-python
    steps:
    - name: ssh to restart python
      uses: fifsky/ssh-action@master
      working-directory: python
      with:
        command: |
          git pull origin master
          pip install -r requirements.txt
          forever restart -c 'python app.py' .
        host: pythonAI.duncantang.dev
        user: ubuntu
        key: ${{secrets.PYTHON_SSH_PRIVATE_KEY}}